### ISSUE TITLE
Error building page when adding ChartsPlugin

### ISSUE THREAD

**Issue by steoj** [timvink/mkdocs-charts-plugin#14]
Thanks so much for a plugin that might just solve quite a few problems for me.

I'm building a docs site running in a docker container, but when adding configs for charts plugin, I get the error: 
`ERROR    -  Error building page 'index.md': 'ChartsPlugin' object has no attribute 'homepage'`
Builds and works fine before adding config changes for charts-plugin

Hopefully I've set up the Dockerfile and the mkdocs.yaml correctly:

```dockerfile
FROM squidfunk/mkdocs-material as BUILD
RUN pip3 install mkdocs-charts-plugin
RUN pip3 install mkdocs-git-revision-date-plugin
RUN pip3 install mkdocs-macros-plugin
RUN pip3 install mkdocs-video
WORKDIR /mkdocs
COPY . .
RUN mkdocs build
```

mkdocs.yaml (part of):
```yaml
...
# Extensions, do not edit
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

# To add css
extra_css:
  - 'stylesheets/extra.css'
  - 'https://unpkg.com/mermaid/dist/mermaid.css'

# To support PyMdown
extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

# Enable search functionality
plugins:
  - mkdocs-video:
      css_style:
        width: "850px"
        height: "478px"
  - search:
      separator: '[\s]+'
      lang: en
      prebuild_index: true
  - git-revision-date
  - charts

```

Still I'm getting the error during build time:
```text
#0 3.005 ERROR    -  Error building page 'index.md': 'ChartsPlugin' object has no attribute 'homepage'
#0 3.005 Traceback (most recent call last):
#0 3.005   File "/usr/local/bin/mkdocs", line 8, in <module>
#0 3.005     sys.exit(cli())
#0 3.006              ^^^^^
#0 3.006   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
#0 3.006     return self.main(*args, **kwargs)
#0 3.006            ^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 3.006   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
#0 3.007     rv = self.invoke(ctx)
#0 3.007          ^^^^^^^^^^^^^^^^
#0 3.007   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
#0 3.007     return _process_result(sub_ctx.command.invoke(sub_ctx))
#0 3.007                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 3.007   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
#0 3.008     return ctx.invoke(self.callback, **ctx.params)
#0 3.008            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 3.008   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
#0 3.008     return __callback(*args, **kwargs)
#0 3.008            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 3.008   File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 250, in build_command
#0 3.009     build.build(cfg, dirty=not clean)
#0 3.009   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 329, in build
#0 3.009     _build_page(file.page, config, doc_files, nav, env, dirty)
#0 3.009   File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 234, in _build_page
#0 3.009     output = config.plugins.run_event('post_page', output, page=page, config=config)
#0 3.009              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 3.009   File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 520, in run_event
#0 3.009     result = method(item, **kwargs)
#0 3.010              ^^^^^^^^^^^^^^^^^^^^^^
#0 3.010   File "/usr/local/lib/python3.11/site-packages/mkdocs_charts_plugin/plugin.py", line 80, in on_post_page
#0 3.010     return self.add_javascript_variables(output, page, config)
#0 3.010            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#0 3.010   File "/usr/local/lib/python3.11/site-packages/mkdocs_charts_plugin/plugin.py", line 105, in add_javascript_variables
#0 3.010     path_to_homepage = self.homepage.url_relative_to(page.file)
#0 3.010                        ^^^^^^^^^^^^^
#0 3.010 AttributeError: 'ChartsPlugin' object has no attribute 'homepage'
```

**Comment by steoj** [comment]
I like to add that the chart I'm trying to display on the index page is:

```text
```vegalite
{
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
      {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
      {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
    ]
  },
  "mark": {"type": "bar", "tooltip": true},
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```
```

**Comment by timvink** [comment]
Looks like my method of determining the path to the homepage is flawed:

https://github.com/timvink/mkdocs-charts-plugin/blob/70296097135a400a0f771e240d7ac839db32a697/mkdocs_charts_plugin/plugin.py#L65-L70

Maybe your site doesn't have a homepage? A quick fix might be added an `index.md` , but I should really look into this again

**Comment by steoj** [comment]
There is an index.md defined in my mkdocs.yaml:
```yaml
...
# Main navigation menu, edit to create your sub menu; retain main menu.
nav:
  - SPTS:
    - About:                        index.md
    - User guide:
      - Login and Quick Guide:      login_and_quick_guide.md
    - Releases:                     
      - Changelog:                  release/CHANGELOG.md
      - Testlog:                    developer/release/e2e-report/index.html
    - Runbook:                      runbook.md
...
```
and it is located in the docs/ folder. Did I understand your quick fix suggestion correctly?

**Comment by timvink** [comment]
I see. But the index page is not at the top level, but under 'SPTS'. Try adding index.md on the top level in nav. That would be picked up as the homepage, and that url is then used to determine the relative path from a page to the javascript assets.

**Comment by steoj** [comment]
Changing reference to index.md in nav did not help. Same issue.
![image](https://user-images.githubusercontent.com/46670655/235320595-1a665dfd-47eb-476a-ba78-b2b9a6e8b3a3.png)

**Comment by steoj** [comment]
Tried again, and this quick-fix worked! 
![Screenshot 2023-05-02 at 15 02 43](https://user-images.githubusercontent.com/46670655/235674053-98a30bed-075c-48a3-ba87-f2404f42d21a.png)

**Comment by ewellinger** [comment]
I'm also facing a similar error. Moving the `index.md` file to the top level of the nav chart does fix it, but long term this is probably not something I'd like to do as my navigation previously looked like this:

```yaml
nav:
  - Home:
      - index.md
      - Tag Index: tags.md
```

I could look into putting together a PR if that'd be helpful?
