### ISSUE TITLE
set the markdown_extensions from the plugin

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-charts-plugin#2]
instead of a user specifying:

```yaml
markdown_extensions:
  - pymdownx.superfences:
      disable_indented_code_blocks: true
      preserve_tabs: true
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fence_vegalite_custom
```

We might be able to do that via the plugin `on_config()` event.
